--- 
- name: installer git et  nano  sur la machine dev
  hosts: dev
  become: yes
  tasks: 
  - name: mise à jour de apt
    apt:
      update_cache: yes
      name: "{{ item }}"
    loop:
    - nano
    - git
