--- 
- name: installer Docker sur une machine ubuntu
  become: yes
  hosts: prod 
  tasks:
  - name: installer quelques paquets utiles
    apt:
      update_cache: yes
      name: "{{ item }}"
    loop:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common
  
  - name: ajout de la  clé du réferentiel de docker au system
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg   
      state: present
  - name: ajout du réferentiel de docker aux sources de apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: installer docker
    apt:
      update_cache: yes
      name: docker-ce
  - name: ajout de l'utilisateur vagrant au groupe docker
    user:
      name: brahim
      group: docker  
  - name: changer les permissions du fichier /var/run/docker.sock pour pouvoir se connecter avec la commande docker login -u - p
    file:
      path: /var/run/docker.sock
      mode: '777'   
